### ISSUE TITLE
All current NSMnow utilities fail to display the current version (-V)

### ISSUE THREAD

**Issue by apkt** [Security-Onion-Solutions/securityonion-nsmnow-admin-scripts#19]
When using the -V or --version command option the scripts all return:-

/usr/sbin/nsm.....: line xxx: print_version: command not found

This is because the routine in /usr/share/nsmnow/lib-nsm-common-utils is named print_nsmnow_version

Simple fix

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/69943a4b5d02c5b78fe6ee229c4fc964d70588d9
