### ISSUE TITLE
language translation issue in lib-nsm-sensor-utils

### ISSUE THREAD

**Issue by MichaelSpyraKAEFER** [Security-Onion-Solutions/securityonion-nsmnow-admin-scripts#24]
Hi,

we have a Problem in our Environment. They are any different languages installed on the sensor-appliances in different countrys.  But the cleanup will not work!

The lib-nsm-sensor-utils used in line 295 the following Code:
`CUR_USAGE=$(df -P $SENSOR_DIR | grep -v -i filesystem | awk '{print $5}' | tr -d %)`
but in other languages is filesystem not finding (ex. in german = Dateisystem). My Suggestion is:
`CUR_USAGE=$(df -P $SENSOR_DIR | sed -n '1!p' | awk '{print $5}' | tr -d %)`
No matter which language is in use, the first line will not be Display.

Thanks for your great work!!

best regards

    Michael

**Comment by dougburks** [comment]
Hi @MichaelSpyraKAEFER ,

First, please note that we only support the English language at this time:
https://securityonion.readthedocs.io/en/latest/installation.html?highlight=english#language

I went ahead and patched `lib-nsm-sensor-utils` replacing the `grep` with `tail -1`.  Please test the new version and let us know if it works for you:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/blob/master/usr/lib/nsmnow/lib-nsm-sensor-utils

Thanks!

**Comment by MichaelSpyraKAEFER** [comment]
Thx for your quick support!!
