### ISSUE TITLE
Snort snaplength not working for jumbo packets

### ISSUE THREAD

**Issue by bombblaster007** [Security-Onion-Solutions/securityonion-nsmnow-admin-scripts#29]
I am using Snort in Ubuntu 18.04 as a virtual machine in VMWare. I wish to process packets greater than 1500 bytes which is the standard MTU of ethernet networks in Linux. I did:

1. Allowed jumbo packets in the Device Manager properties of the VMWare Virtual Ethernet Adapter.
2. Defined MTU to be 9000 in Ubuntu by the command "sudo ifconfig ens33 mtu 9000" (ens33 is my ethernet interface)
3. Changed "config snaplen:9000" in snort.conf file.

Even after doing all this, Snort still cannot analyse jumbo packets and drop if the packet size goes beyond 1500. Any suggestions on what I am doing wrong?

**Comment by dougburks** [comment]
If you're using Snort in Ubuntu 18.04, then you're not using Security Onion and we can't help you. You might want to reach out to the Snort folks?
