### ISSUE TITLE
Scripts start/restart errors on systems with ethXX (2 or more numbers)

### ISSUE THREAD

**Issue by swiip81** [Security-Onion-Solutions/securityonion-nsmnow-admin-scripts#9]
Hello,

During `nsm_sensor --start` or  `nsm_sensor --restart`  errors are displayed on systems with more than 10 network interfaces because `server-eth1`  string exists in `server-eth10 , server-eth11 ....`

<pre>* starting: snort_agent (sguil)                                                                                                                            [  OK  ]
/usr/sbin/nsm_sensor_ps-restart: line 512: let: 2
3
4
5
6
7
8: syntax error in expression (error token is "3
4
5
6
7
8")
sed: -e expression #1, char 60: unterminated `s' command
sed: -e expression #1, char 30: unterminated `s' command
  * stopping: suricata (alert data)</PRE>

I fix that by just matching a space after it in the grep here `vim +520 /usr/sbin/nsm_sensor_ps-start ; vim +512 /usr/sbin/nsm_sensor_ps-restart`

<PRE>--  CLUSTER_ID=`grep -n $SENSOR /etc/nsm/sensortab |cut -d\: -f1`; let CLUSTER_ID+=50
++  CLUSTER_ID=`grep -n "$SENSOR "  /etc/nsm/sensortab |cut -d\: -f1`; let CLUSTER_ID+=50</PRE>

Best regards

**Comment by dougburks** [comment]
Thanks, @swiip81 !

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/75ccaef1ae52f9cd745890b3169a4571733ce579
